CREATE TABLE LOGS(LOGId int, Timestamp DATETIME);
---CREATING THE TRIGGER TO ADD VALUES TOT THE LOG TABLE WHENEVER WE MAKE CHANGES IN THE STUDENT MARKS TABLE
CREATE OR ALTER TRIGGER MARKSTRIGGER 
ON StudentMarks
AFTER INSERT
AS
INSERT INTO LOGS VALUES ((SELECT COUNT(*) FROM LOGS)+1, SYSDATETIME());

SELECT * FROM StudentMarks;

--WE ARE INSERTING THE VALUES TO STUDENTMARKS
INSERT INTO StudentMarks VALUES (29,'Mech', 105, 76.20,'n27@gmail.com');

--NOW IF WE SELECT THE THE VALUES TO DISPLAY WE CAN SEE THE ENTRY CREATED USING TRIGGER
select * fROM LOGS;

go
/*
CREATE TABLE LOGS ( ID INT , TIMESTAMP DATETIME );ALTER TABLE LOGS ADD UNIQUEID UNIQUEIDENTIFIER ;SELECT * FROM LOGS;CREATE OR ALTER TRIGGER STUDENTTRIGGERON MARKSAFTER INSERTASINSERT INTO LOGS VALUES ( 0 , CURRENT_TIMESTAMP , NEWID() );DROP TRIGGER STUDENTTRIGGER;SELECT * FROM MARKS;INSERT INTO MARKS VALUES ( 60265 , 0 , 100 );*/